# Generated by Django 3.1.5 on 2021-01-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasajero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasajero',
            options={'verbose_name_plural': 'Pasajeros'},
        ),
    ]
