# Generated by Django 3.1.5 on 2021-01-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chofer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chofer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chofer',
            name='telefono',
        ),
        migrations.AddField(
            model_name='chofer',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
