# Generated by Django 3.1.5 on 2021-01-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chofer', '0002_auto_20210125_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='email',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chofer',
            name='telefono',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
