# Generated by Django 3.1.5 on 2021-01-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chofer', '0003_auto_20210125_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='run',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
