# Generated by Django 3.1.5 on 2021-01-30 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trayecto', '0001_initial'),
        ('pasajero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('num_asiento', models.IntegerField()),
                ('pasajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasajero.pasajero')),
                ('trayecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trayecto.trayecto')),
            ],
            options={
                'verbose_name_plural': 'Viajes',
            },
        ),
    ]
