# Generated by Django 3.1.5 on 2021-01-25 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trayecto', '0001_initial'),
        ('viaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='trayecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trayecto.trayecto'),
        ),
    ]
