# Generated by Django 3.1.5 on 2021-01-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasajero', '0001_initial'),
        ('viaje', '0002_auto_20210125_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='pasajero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pasajero.pasajero'),
        ),
    ]
