# Generated by Django 3.1.5 on 2021-01-25 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trayecto', '0001_initial'),
        ('pasajero', '0001_initial'),
        ('viaje', '0003_auto_20210125_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajero.pasajero'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='trayecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trayecto.trayecto'),
        ),
    ]
