# Generated by Django 3.1.5 on 2021-01-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasajero', '0001_initial'),
        ('viaje', '0004_auto_20210125_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='cantidad',
            new_name='num_asiento',
        ),
        migrations.AddField(
            model_name='viaje',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='pasajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pasajero.pasajero'),
        ),
    ]
