# Generated by Django 3.1.5 on 2021-01-30 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chofer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10)),
                ('disponible', models.BooleanField(default=True)),
                ('cantidad_asientos', models.IntegerField(default=10)),
                ('chofer_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chofer.chofer')),
            ],
            options={
                'verbose_name_plural': 'Buses',
            },
        ),
    ]
