# Generated by Django 3.1.5 on 2021-01-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chofer', '0002_auto_20210125_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10)),
                ('disponible', models.BooleanField(default=True)),
                ('chofer_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chofer.chofer')),
            ],
        ),
    ]
