# Generated by Django 3.1.5 on 2021-01-30 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=70)),
                ('destino', models.CharField(max_length=70)),
                ('precio', models.IntegerField(default=0)),
                ('fecha_salida', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_llegada', models.DateTimeField(auto_now=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('bus_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus.bus')),
            ],
            options={
                'verbose_name_plural': 'Trayectos',
            },
        ),
    ]
