# Generated by Django 3.1.5 on 2021-01-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=70)),
                ('destino', models.CharField(max_length=70)),
                ('precio', models.IntegerField()),
                ('fecha_salida', models.DateField()),
                ('fecha_llegada', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
                ('bus_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
            ],
        ),
    ]
