# Generated by Django 3.1.5 on 2021-01-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20210125_1939'),
        ('trayecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trayecto',
            name='bus_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus.bus'),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='fecha_llegada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='fecha_salida',
            field=models.DateTimeField(),
        ),
    ]
