# Generated by Django 3.1.5 on 2021-01-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayecto', '0002_auto_20210131_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trayecto',
            name='fecha_llegada',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='fecha_salida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
